sudo: required
services:
  - docker

before_install:
  - docker build -t vinaykumar785557/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vinaykumar785557/react-test npm test

# - docker run USERNAME/react-test npm test -- --coverage
# use ctrl+/ to add a comment in yaml file.

after_success:
  - docker build -t vinaykumar785557/multi-client ./client
  - docker build -t vinaykumar785557/multi-nginx ./nginx
  - docker build -t vinaykumar785557/multi-server ./server
  - docker build -t vinaykumar785557/multi-worker ./worker
