sudo: required
services:
  - docker

before_install:
  - docker build -t vinaykumar785557/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vinaykumar785557/react-test npm test
  # - docker run USERNAME/react-test npm test -- --coverage

# use ctrl+/ to add a comment in yaml file.

after_success:
  - docker build -t vinaykumar785557/multi-client ./client
  - docker build -t vinaykumar785557/multi-nginx ./nginx
  - docker build -t vinaykumar785557/multi-server ./server
  - docker build -t vinaykumar785557/multi-worker ./worker
  # log in to the docker cli
  # put your login details in travis ci environmental variable
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to your docker hub
  - docker push vinaykumar785557/multi-client
  - docker push vinaykumar785557/multi-nginx
  - docker push vinaykumar785557/multi-server
  - docker push vinaykumar785557/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
